- name: Install php-fpm & php extensions
  become: true
  apt: pkg={{ item }} state=installed update_cache=true
  with_items:
  - php-fpm
  - php-gd
  - php-curl
  - php-mysql
  - php-dom
  - php-xml

- name: Download the install files
  get_url: url='https://github.com/JonLMyers/MetroTransit.zip' dest='/var/www/html/master.zip'
  register: result

- unarchive:
    src: /var/www/html/master.zip
    dest: /var/www/html/
    remote_src: True

- name: Restart php-fpm
  become: yes
  service: name=php7.0-fpm state=restarted