---
- hosts: php
  sudo: yes

  tasks:

  - name: install packages
    apt: name={{ item }} update_cache=yes state=latest
    with_items:
      - git
      - apache2
      - php
      - php-mcrypt 
      - mysql-server
      - php-mysql
      - libapache2-mod-php 
      - libapache 
